######################################################################
# Automatically generated by qmake (3.0) Wed Jun 8 13:52:19 2016
######################################################################

TEMPLATE = app
TARGET = exam
INCLUDEPATH += .

# Input
HEADERS += GUI.h \
           Programmer.h \
           StatusException.h \
           Task.h \
           TaskController.h \
           TaskRepository.h
SOURCES += main.cpp
