new_local_repository(
    name = "qt",
    build_file = "BUILD.qt",
    path = "/usr/include/qt",
)

new_http_archive(
    name = "eigen",
    build_file = "BUILD.eigen",
    strip_prefix = "eigen-eigen-5a0156e40feb",
    url = "http://bitbucket.org/eigen/eigen/get/3.3.4.zip",
)
