new_local_repository(
    name = "qt",
    build_file = "BUILD.qt",
    path = "/usr/include/qt",
)

new_local_repository(
    name = "linux_ntl",
    build_file = "BUILD.ntl",
    path = "/usr/lib",
)

bind(
    name = "ntl",
    actual = "@linux_ntl//:ntl",
)

new_http_archive(
    name = "eigen",
    build_file = "BUILD.eigen",
    strip_prefix = "eigen-eigen-5a0156e40feb",
    url = "http://bitbucket.org/eigen/eigen/get/3.3.4.zip",
)

new_http_archive(
    name = "flint",
    build_file = "BUILD.flint",
    strip_prefix = "flint-2.5.2",
    url = "http://www.flintlib.org/flint-2.5.2.zip",
)

git_repository(
    name = "com_github_nelhage_boost",
    commit = "d6446dc9de6e43b039af07482a9361bdc6da5237",
    remote = "https://github.com/nelhage/rules_boost",
)

load("@com_github_nelhage_boost//:boost/boost.bzl", "boost_deps")

boost_deps()
