######################################################################
# Automatically generated by qmake (3.0) Tue May 24 21:20:41 2016
######################################################################

TEMPLATE = app
TARGET = ex
INCLUDEPATH += .
QT = core gui widgets

# Input
SOURCES += main.cpp
