######################################################################
# Automatically generated by qmake (3.0) Tue May 24 12:17:03 2016
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += core gui widgets

# Input
SOURCES += hello.cpp
