######################################################################
# Automatically generated by qmake (3.0) Wed Jun 8 00:15:35 2016
######################################################################

TEMPLATE = app
TARGET = practical-exam-simulation
INCLUDEPATH += .

# Input
HEADERS += GUI.h \
           controllers/GradingController.h \
           models/Student.h \
           models/Teacher.h \
           repositories/GradingRepository.h
SOURCES += main.cpp
